kind: Service
apiVersion: v1
metadata:
  name: nats-gui
  namespace: nats
  labels:
    app: nats
spec:
  type: NodePort
  selector:
    app: nats
  ports:
  - port: 4222
    name: nats
    targetPort: 4222
  - port: 8222
    name: nats-a
    targetPort: 8222    

---
