apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: events
data:
  fluent.conf: |
      # Forwarded from fluentd
      <source>
        @type nats
        tag nats
        host  "#{ENV['NATS_HOST']}"
        port 4222
        queues *.>
        ssl false

      </source>
      
      <match **>
           @type elasticsearch
           @id out_es
           @log_level info
           include_tag_key true
           host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
           port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
           scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
           logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
           logstash_dateformat "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_DATEFORMAT'] || '%Y.%m.%d'}"
           logstash_format "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT'] || 'true'}"
           index_name "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME'] || 'logstash'}"
      </match>
