apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "docker.elastic.co/elasticsearch/elasticsearch:7.7.0"
          imagePullPolicy: Always
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1G"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
          livenessProbe:
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200


---
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-node
  namespace: elastic
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200

