kind: Service
apiVersion: v1
metadata:
  name: fluentd-forward
  namespace: events
  labels:
    app: fluentd-forward
spec:
  type: ClusterIP
  selector:
    app: fluentd-forward
  ports:
  - port: 24224
    name: fluentd-forward
    targetPort: 24224
  - port: 24231
    name: metrics
    targetPort: 24231
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-forward
  namespace: events
spec:
  selector:
    matchLabels:
      app: fluentd-forward
  replicas: 1
  template:
    metadata:
      labels:
        app: fluentd-forward
    spec:
      volumes:
      - name: fluentd-forward-config
        configMap:
          name: fluentd-forward-config
      containers:
      - name: fluentd-forward
        image: ctael5co/fluentd
        command: ["fluentd"]
        args: ["-c", "/fluentd/etc/fluent.conf", "-v"]
        imagePullPolicy: Always
        ports:
        - containerPort: 24224
          name: fluentd-forward
        - containerPort: 24231
          name: metrics
        env:
        - name: ELASTICSEARCH_URL
          value: "elasticsearch.elastic.svc"
        - name: NATS_HOST
          value: "nats.nats.svc"
        volumeMounts:
        - name: fluentd-forward-config
          mountPath: /fluentd/etc
          readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-forward-config 
  namespace: events
data:
  fluent.conf: |
        <source>
          type forward
          port 24224
          bind 0.0.0.0
        </source>

        <match **>
           @type nats
           tag nats
           host nats.nats.svc
           port 4222
           ssl false
        </match>

        <match **>
           @type stdout
        </match>

